server:
  port: 9080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql8-test01-mysql-master-3489.ot1.gz.paas.cvtecs.com:3489/chatdata
    username: chatdata
    password: Ae?15LjU

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml

authentication:
  enable: true
  exclude:
    path: /api/auth/user/register,/api/auth/user/login
  token:
    timeout: 86400000
    http:
      header:
        key: Authorization
logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG

s2:
  pyllm:
    url: http://127.0.0.1:9092

  parser:
    url: ${s2.pyllm.url}
    exemplar-recall:
      number: 10
    few-shot:
      number: 5
    self-consistency:
      number: 5
    multi-turn:
      enable: true

  corrector:
    additional:
      information: true

  functionCall:
    url: ${s2.pyllm.url}

  embedding:
    url: ${s2.pyllm.url}
    persistent:
      path: /tmp

  demo:
    names: S2VisitsDemo,S2ArtistDemo
    enableLLM: true

  langchain4j:
    #1.chat-model
    chat-model:
      provider: open_ai
      openai:
        # Replace with your LLM configs
        # Note: The default API key `demo` is provided by langchain4j community
        #       which limits 1000 tokens per request.
        base-url: https://aihubmix.com/v1
        api-key: sk-lZ9dlL3R9rgG5zYg62057024228f4d8b851eEeC407F219D8
        model-name: gpt-3.5-turbo
        temperature: 0.0
        timeout: PT60S
    #2.embedding-model
    #2.1 in_memory(default)
    embedding-model:
      provider: in_process
    #      inProcess:
    #        modelPath: /data/model.onnxe
    #        vocabularyPath: /data/onnx_vocab.txt
    #        shibing624/text2vec-base-chinese
    #2.2 open_ai
    #  embedding-model:
    #    provider: open_ai
    #    openai:
    #      api-key: api_key
    #      modelName: all-minilm-l6-v2.onnx

    #2.2 hugging_face
    #  embedding-model:
    #    provider: hugging_face
    #    hugging-face:
    #      access-token: hg_access_token
    #      model-id: sentence-transformers/all-MiniLM-L6-v2
    #      timeout: 1h

#cas单点登录
cas:
  # prefixUrl: https://op.cvte.com/d72f1f3c12904d359e1de7e99cac61e8
  prefixUrl: https://op-fat.cvte.com/b9114441c4544c5093ce5754a9f8b6c4
