server:
  port: 9080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  h2:
    console:
      path: /h2-console/semantic
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql8-test01-mysql-master-3489.ot1.gz.paas.cvtecs.com:3489/chatdata
    username: chatdata
    password: Ae?15LjU

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml

logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG
# swagger配置
swagger:
  title: 'SuperSonic平台接口文档'
  base:
    package: com.tencent.supersonic
  description: 'SuperSonic平台接口文档'
  url: ''
  contact:
    name:
    email:
    url: ''
  version: 3.0

#cas单点登录
cas:
  # prefixUrl: https://op.cvte.com/d72f1f3c12904d359e1de7e99cac61e8
  prefixUrl: https://op-fat.cvte.com/b9114441c4544c5093ce5754a9f8b6c4

dify:
  url: https://dify.cvte.com/v1/chat-messages
  key: Bearer app-iPTMT6gRbDvx5K9tlAa8cfrE
