langchain4j:
  open-ai:
    chat-model:
      # Replace with your LLM configs
      # Note: The default API key `demo` is provided by langchain4j community
      #       which limits 1000 tokens per request.
      base-url: ${OPENAI_API_BASE:https://aihubmix.com/v1}
      api-key: ${OPENAI_API_KEY:sk-lZ9dlL3R9rgG5zYg62057024228f4d8b851eEeC407F219D8}
      model-name: ${OPENAI_MODEL_NAME:gpt-3.5-turbo}
      temperature: ${OPENAI_TEMPERATURE:0.0}
      timeout: ${OPENAI_TIMEOUT:PT60S}
  #    embedding-model:
  #      base-url: ${OPENAI_API_BASE:https://aihubmix.com/v1}
  #      api-key: ${OPENAI_API_KEY:sk-lZ9dlL3R9rgG5zYg62057024228f4d8b851eEeC407F219D8}
  #      model-name: ${OPENAI_MODEL_NAME:gpt-3.5-turbo}
  #  dashscope:
  #    chat-model:
  #      api-key: ${OPENAI_API_KEY:demo}
  #      model-name: qwen-max-1201
  #    embedding-model:
  #      api-key: ${OPENAI_API_KEY:demo}
#  in-memory:
#    #    embedding-model:
#    #      model-name: bge-small-zh
#    #modelPath: /data/model.onnx
#    #vocabularyPath: /data/onnx_vocab.txt
#    embedding-store:
#      file-path: /tmp
  chroma:
    embedding-store:
      baseUrl: http://0.0.0.0:8000
      timeout: 120s

  zhipu:
    #    chat-model:
    #      base-url: ${ZHIPU_API_BASE:https://open.bigmodel.cn/api/paas/v4/}
    #      api-key: ${ZHIPU_API_KEY:9f822561220238c490050e6e60896e95.XCG5eL4X8ni1CjnB}
    #      model-name: ${ZHIPU_MODEL_NAME:glm-4}
    #      temperature: ${ZHIPU_TEMPERATURE:0.0}
    #      timeout: ${ZHIPU_TIMEOUT:PT60S}
#    embedding-model:
#      base-url: ${ZHIPU_API_BASE:https://open.bigmodel.cn/}
#      api-key: ${ZHIPU_API_KEY:9f822561220238c490050e6e60896e95.XCG5eL4X8ni1CjnB}
#      model: ${ZHIPU_MODEL_NAME:embedding-2}
#
  jina:
    embedding-model:
      base-url: ${JINA_API_BASE:http://10.10.20.161:9997/}
      model: ${JINA_MODEL_NAME:12a22820-9888-11ee-b4f6-161d11c9987a}

#  ollama:
#    chat-model:
#      base-url: http://localhost:11434
#      api-key: demo
#      model-name: qwen:0.5b
#      temperature: 0.0
#      timeout: PT60S

#  chroma:
#    embedding-store:
#      baseUrl: http://0.0.0.0:8000
#      timeout: 120s

#  milvus:
#    embedding-store:
#      host: localhost
#      port: 2379
#      uri: http://0.0.0.0:19530
#      token: demo
#      dimension: 512
#      timeout: 120s