langchain4j:
  open-ai:
    chat-model:
      # Replace with your LLM configs
      # Note: The default API key `demo` is provided by langchain4j community
      #       which limits 1000 tokens per request.
      base-url: https://api.openai.com/v1
      api-key: demo
      model-name: gpt-3.5-turbo
      temperature: 0.0
      timeout: PT60S
  in-memory:
    embedding-model:
      model-name: bge-small-zh
    embedding-store:
      persist-path: /tmp